export const demoData = {
  products: [
    {
      id: 1,
      name: "UPL NPK 20:20:20 Fertilizer 50kg",
      category: "Fertilizers",
      brand: "UPL",
      description: "Balanced NPK fertilizer for all crops. Promotes healthy root and shoot growth.",
      price: 1250,
      discount_price: 1100,
      stock_quantity: 150,
      rating: 4.7,
      review_count: 42,
      sales_count: 235,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=a%2050kg%20bag%20of%20UPL%20NPK%20fertilizer%2C%20agricultural%20product%2C%20realistic&image_size=square",
      seller_name: "GreenAgro Suppliers",
      seller_location: "Vadodara, Gujarat",
      unit: "Bag",
      availability: true,
      shopId: 1,
      shopName: "GreenAgro Suppliers"
    },
    {
      id: 2,
      name: "Bayer Confidor Insecticide 250ml",
      category: "Pesticides",
      brand: "Bayer",
      description: "Systemic insecticide for controlling sucking pests like aphids and jassids.",
      price: 850,
      discount_price: 780,
      stock_quantity: 80,
      rating: 4.8,
      review_count: 56,
      sales_count: 198,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Bayer%20Confidor%20insecticide%20bottle%2C%20agricultural%20chemical&image_size=square",
      seller_name: "Krishi Seva Kendra",
      seller_location: "Vadodara, Gujarat",
      unit: "Bottle",
      availability: true,
      shopId: 2,
      shopName: "Krishi Seva Kendra"
    },
    {
      id: 3,
      name: "Syngenta Hybrid Cotton Seeds 450g",
      category: "Seeds",
      brand: "Syngenta",
      description: "High-yielding Bt cotton seeds with excellent boll retention.",
      price: 950,
      discount_price: 890,
      stock_quantity: 200,
      rating: 4.6,
      review_count: 38,
      sales_count: 412,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Syngenta%20hybrid%20cotton%20seeds%20packet%2C%20agriculture&image_size=square",
      seller_name: "Anand Seeds Center",
      seller_location: "Anand, Gujarat",
      unit: "Packet",
      availability: true,
      shopId: 3,
      shopName: "Anand Seeds Center"
    },
    {
      id: 4,
      name: "IFFCO Urea 50kg",
      category: "Fertilizers",
      brand: "IFFCO",
      description: "Premium quality urea for maximum nitrogen supply to crops.",
      price: 380,
      discount_price: 350,
      stock_quantity: 500,
      rating: 4.9,
      review_count: 120,
      sales_count: 890,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=IFFCO%20urea%2050kg%20bag%2C%20fertilizer&image_size=square",
      seller_name: "IFFCO Kisan Sewa",
      seller_location: "Vadodara, Gujarat",
      unit: "Bag",
      availability: true,
      shopId: 4,
      shopName: "IFFCO Kisan Sewa"
    },
    {
      id: 5,
      name: "Coromandel Mancozeb Fungicide 1kg",
      category: "Pesticides",
      brand: "Coromandel",
      description: "Broad-spectrum fungicide for controlling blight and rust diseases.",
      price: 280,
      discount_price: 250,
      stock_quantity: 180,
      rating: 4.5,
      review_count: 45,
      sales_count: 340,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Coromandel%20mancozeb%20fungicide%20packet&image_size=square",
      seller_name: "AgroChem Solutions",
      seller_location: "Vadodara, Gujarat",
      unit: "Packet",
      availability: true,
      shopId: 5,
      shopName: "AgroChem Solutions"
    },
    {
      id: 6,
      name: "Tata Agrico Hand Tractor Tiller",
      category: "Farm Equipment",
      brand: "Tata Agrico",
      description: "Powerful mini tiller for small and medium farms, easy to operate.",
      price: 45000,
      discount_price: 42000,
      stock_quantity: 15,
      rating: 4.7,
      review_count: 22,
      sales_count: 45,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Tata%20Agrico%20hand%20tractor%20tiller%2C%20farm%20equipment&image_size=square",
      seller_name: "Tata Agrico Store",
      seller_location: "Vadodara, Gujarat",
      unit: "Piece",
      availability: true,
      shopId: 6,
      shopName: "Tata Agrico Store"
    },
    {
      id: 7,
      name: "Jain Irrigation Drip Kit 1 Acre",
      category: "Irrigation",
      brand: "Jain Irrigation",
      description: "Complete drip irrigation system for 1 acre, water-saving up to 70%.",
      price: 12500,
      discount_price: 11500,
      stock_quantity: 25,
      rating: 4.8,
      review_count: 35,
      sales_count: 78,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Jain%20Irrigation%20drip%20kit%2C%20irrigation%20system&image_size=square",
      seller_name: "Jain Irrigation Center",
      seller_location: "Vadodara, Gujarat",
      unit: "Kit",
      availability: true,
      shopId: 7,
      shopName: "Jain Irrigation Center"
    },
    {
      id: 8,
      name: "Organic Vermicompost 25kg",
      category: "Organic Products",
      brand: "Green Organic",
      description: "Rich earthworm compost for organic farming, improves soil health.",
      price: 450,
      discount_price: 400,
      stock_quantity: 300,
      rating: 4.6,
      review_count: 67,
      sales_count: 520,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=organic%20vermicompost%2025kg%20bag&image_size=square",
      seller_name: "Organic Farms India",
      seller_location: "Anand, Gujarat",
      unit: "Bag",
      availability: true,
      shopId: 9,
      shopName: "Organic Farms India"
    },
    {
      id: 9,
      name: "Cattle Feed Concentrate 50kg",
      category: "Animal Feed",
      brand: "Amul Feed",
      description: "Nutritious cattle feed for high milk yield, balanced nutrition.",
      price: 1100,
      discount_price: 1000,
      stock_quantity: 250,
      rating: 4.7,
      review_count: 89,
      sales_count: 670,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Amul%20cattle%20feed%2050kg%20bag&image_size=square",
      seller_name: "Amul Feed Center",
      seller_location: "Vadodara, Gujarat",
      unit: "Bag",
      availability: true,
      shopId: 10,
      shopName: "Amul Feed Center"
    },
    {
      id: 10,
      name: "Knapsack Sprayer 16L",
      category: "Tools",
      brand: "Neptune",
      description: "Manual backpack sprayer for pesticide and fertilizer application.",
      price: 850,
      discount_price: 780,
      stock_quantity: 120,
      rating: 4.5,
      review_count: 54,
      sales_count: 280,
      image_url: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=knapsack%20sprayer%2016L%2C%20agricultural%20tool&image_size=square",
      seller_name: "Agro Tools Hub",
      seller_location: "Vadodara, Gujarat",
      unit: "Piece",
      availability: true,
      shopId: 11,
      shopName: "Agro Tools Hub"
    }
  ],
  stores: [
    {
      store_id: 1,
      store_name: "GreenAgro Suppliers",
      owner_name: "Rajesh Patel",
      address: "Alkapuri, Vadodara, Gujarat",
      latitude: 22.3072,
      longitude: 73.1818,
      phone: "+919876543210",
      email: "info@greenagro.in",
      rating: 4.7,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=agricultural%20supply%20store%20exterior%2C%20Vadodara&image_size=square",
      opening_time: "08:00",
      closing_time: "20:00",
      type: "General Agro Store",
      status: "active",
      name: "GreenAgro Suppliers",
      lat: 22.3072,
      lng: 73.1818
    },
    {
      store_id: 2,
      store_name: "Krishi Seva Kendra",
      owner_name: "Mukesh Shah",
      address: "Manjalpur, Vadodara, Gujarat",
      latitude: 22.29,
      longitude: 73.17,
      phone: "+919876543211",
      email: "ksk@krishi.in",
      rating: 4.6,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=krishi%20seva%20kendra%20store%20front&image_size=square",
      opening_time: "07:30",
      closing_time: "19:30",
      type: "Agro Chemical Store",
      status: "active",
      name: "Krishi Seva Kendra",
      lat: 22.29,
      lng: 73.17
    },
    {
      store_id: 3,
      store_name: "Anand Seeds Center",
      owner_name: "Amit Patel",
      address: "Anand, Gujarat",
      latitude: 22.5645,
      longitude: 72.9289,
      phone: "+919876543212",
      email: "seeds@anand.in",
      rating: 4.8,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=seed%20store%20interior%2C%20Anand&image_size=square",
      opening_time: "08:00",
      closing_time: "19:00",
      type: "Seed Store",
      status: "active",
      name: "Anand Seeds Center",
      lat: 22.5645,
      lng: 72.9289
    },
    {
      store_id: 4,
      store_name: "IFFCO Kisan Sewa",
      owner_name: "Suresh Desai",
      address: "Vasna Road, Vadodara, Gujarat",
      latitude: 22.31,
      longitude: 73.19,
      phone: "+919876543213",
      email: "iffco@kisan.in",
      rating: 4.9,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=IFFCO%20kisan%20sewa%20store&image_size=square",
      opening_time: "07:00",
      closing_time: "20:30",
      type: "Fertilizer Shop",
      status: "active",
      name: "IFFCO Kisan Sewa",
      lat: 22.31,
      lng: 73.19
    },
    {
      store_id: 5,
      store_name: "AgroChem Solutions",
      owner_name: "Prakash Mehta",
      address: "Race Course, Vadodara, Gujarat",
      latitude: 22.3,
      longitude: 73.185,
      phone: "+919876543214",
      email: "agrochem@solutions.in",
      rating: 4.5,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=agrochemical%20shop%20exterior&image_size=square",
      opening_time: "08:30",
      closing_time: "19:00",
      type: "Agro Chemical Store",
      status: "active",
      name: "AgroChem Solutions",
      lat: 22.3,
      lng: 73.185
    },
    {
      store_id: 6,
      store_name: "Tata Agrico Store",
      owner_name: "Harshad Patel",
      address: "Fatehgunj, Vadodara, Gujarat",
      latitude: 22.32,
      longitude: 73.2,
      phone: "+919876543215",
      email: "tata@agrico.in",
      rating: 4.7,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Tata%20Agrico%20store%20front&image_size=square",
      opening_time: "09:00",
      closing_time: "19:30",
      type: "Farm Equipment Dealer",
      status: "active",
      name: "Tata Agrico Store",
      lat: 22.32,
      lng: 73.2
    },
    {
      store_id: 7,
      store_name: "Jain Irrigation Center",
      owner_name: "Vikram Jain",
      address: "Sama Road, Vadodara, Gujarat",
      latitude: 22.315,
      longitude: 73.175,
      phone: "+919876543216",
      email: "jain@irrigation.in",
      rating: 4.8,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=irrigation%20equipment%20store&image_size=square",
      opening_time: "08:00",
      closing_time: "19:00",
      type: "Irrigation Store",
      status: "active",
      name: "Jain Irrigation Center",
      lat: 22.315,
      lng: 73.175
    },
    {
      store_id: 8,
      store_name: "Organic Farms India",
      owner_name: "Anita Shah",
      address: "Anand, Gujarat",
      latitude: 22.55,
      longitude: 72.93,
      phone: "+919876543218",
      email: "organic@farms.in",
      rating: 4.7,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=organic%20farming%20store%20interior&image_size=square",
      opening_time: "08:30",
      closing_time: "18:30",
      type: "Organic Farming Store",
      status: "active",
      name: "Organic Farms India",
      lat: 22.55,
      lng: 72.93
    },
    {
      store_id: 9,
      store_name: "Amul Feed Center",
      owner_name: "Bhavin Patel",
      address: "Gotri, Vadodara, Gujarat",
      latitude: 22.318,
      longitude: 73.165,
      phone: "+919876543219",
      email: "amul@feed.in",
      rating: 4.8,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=Amul%20feed%20center%20store&image_size=square",
      opening_time: "07:30",
      closing_time: "20:00",
      type: "Animal Feed Store",
      status: "active",
      name: "Amul Feed Center",
      lat: 22.318,
      lng: 73.165
    },
    {
      store_id: 10,
      store_name: "Agro Tools Hub",
      owner_name: "Kaushik Mehta",
      address: "Navapura, Vadodara, Gujarat",
      latitude: 22.295,
      longitude: 73.188,
      phone: "+919876543220",
      email: "tools@agro.in",
      rating: 4.6,
      store_image: "https://coresg-normal.trae.ai/api/v1/text_to_image?prompt=agricultural%20tools%20shop&image_size=square",
      opening_time: "08:30",
      closing_time: "19:30",
      type: "Tool Store",
      status: "active",
      name: "Agro Tools Hub",
      lat: 22.295,
      lng: 73.188
    }
  ]
};
