<?php
session_start();
include '_db_connect.php';

if (!isset($_SESSION["shop_userid"])) {
    header("Location: shop_login.php");
    exit();
}

$user_id = $_SESSION["shop_userid"];

// Fetch Shop Details to get ID
$shop_res = mysqli_query($conn, "SELECT shop_id FROM shops WHERE owner_user_id = '$user_id'");
$shop = mysqli_fetch_assoc($shop_res);

if (!$shop) {
    echo "<div style='padding:2rem; text-align:center; color:red;'>Error: No shop found linked to this account. Please contact admin.</div>";
    exit(); 
}

$shop_id = $shop['shop_id'];

// Handle Product Add
$message = "";
if (isset($_POST['add_product'])) {
    $p_name = mysqli_real_escape_string($conn, $_POST['pr_name']);
    $p_price = mysqli_real_escape_string($conn, $_POST['pr_price']);
    $p_qty = mysqli_real_escape_string($conn, $_POST['pr_qty']);
    $p_cat = mysqli_real_escape_string($conn, $_POST['pr_cat']);
    $p_brand = mysqli_real_escape_string($conn, $_POST['pr_brand']);
    $p_desc = mysqli_real_escape_string($conn, $_POST['pr_desc']);
    
    // Auto Identify Unique ID
    // Logic: Find max ID and add 1. If none, start at 1001.
    // However, global unique is safer.
    // Let's generate a random 6 digit number and check.
    $is_unique = false;
    $p_ext_id = 0;
    
    while(!$is_unique) {
        $p_ext_id = mt_rand(100000, 999999);
        $check_sql = "SELECT pr_id FROM product WHERE pr_id = '$p_ext_id'";
        if(mysqli_num_rows(mysqli_query($conn, $check_sql)) == 0) {
            $is_unique = true;
        }
    }

    // Image Upload
    $target_dir = "img/products_img/";
    $img_name_orig = basename($_FILES["pr_img"]["name"]);
    $imageFileType = strtolower(pathinfo($img_name_orig,PATHINFO_EXTENSION));
    
    // Rename image to prevent overwrites and clean name
    $img_name = "pr_" . $p_ext_id . "." . $imageFileType;
    $target_file = $target_dir . $img_name;
    
    if (move_uploaded_file($_FILES["pr_img"]["tmp_name"], $target_file)) {
        // Insert with shop_id
        $sql = "INSERT INTO product (pr_id, pr_name, pr_pr, pr_qu, pr_brand, pr_cat, pr_de, pr_img, pr_img_n, shop_id, created_at) 
                VALUES ('$p_ext_id', '$p_name', '$p_price', '$p_qty', '$p_brand', '$p_cat', '$p_desc', '$target_file', '$img_name', '$shop_id', NOW())";
        
        if (mysqli_query($conn, $sql)) {
            $message = "Product added successfully! System ID: #$p_ext_id";
        } else {
            $message = "Error: " . mysqli_error($conn);
        }
    } else {
        $message = "Failed to upload image.";
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Product - Shop Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="css/admin_style.css">
</head>
<body>

    <?php include 'sidebar_shop.php'; ?>

    <div class="main-content">
        <div class="header-title">
            <h1>Add New Product</h1>
        </div>

        <?php if($message): ?>
            <div style="padding: 1rem; background: <?php echo strpos($message, 'Error') !== false ? '#fee2e2' : '#dcfce7'; ?>; 
                        color: <?php echo strpos($message, 'Error') !== false ? '#b91c1c' : '#15803d'; ?>; 
                        border-radius: 6px; margin-bottom: 1rem;">
                <?php echo $message; ?>
            </div>
        <?php endif; ?>

        <div class="card" style="max-width: 800px;">
            <p style="color: #6b7280; font-size: 0.9rem; margin-bottom: 1.5rem;">
                Fill in the details below. A unique Product ID will be automatically generated by the system.
            </p>
            <form method="post" enctype="multipart/form-data">
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem;">
                    
                    <div class="form-group">
                        <label class="form-label">Product Name</label>
                        <input type="text" name="pr_name" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Price (₹)</label>
                        <input type="number" name="pr_price" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Quantity</label>
                        <input type="number" name="pr_qty" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Brand</label>
                        <input type="text" name="pr_brand" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Category</label>
                        <select name="pr_cat" class="form-control">
                            <option value="1">Electronics</option>
                            <option value="2">Snacks</option>
                            <option value="3">Beverages</option>
                            <option value="4">Household</option>
                            <option value="5">Stationary</option>
                            <option value="6">Medicines</option>
                            <option value="7">Personal Care</option>
                            <option value="8">Groceries</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Product Image</label>
                        <input type="file" name="pr_img" class="form-control" required>
                    </div>

                </div>

                <div class="form-group">
                    <label class="form-label">Description</label>
                    <textarea name="pr_desc" class="form-control" rows="4"></textarea>
                </div>

                <button type="submit" name="add_product" class="btn-primary">Add Product</button>
            </form>
        </div>
    </div>

</body>
</html>
